apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuber.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: kuber
spec:
  replicas: {{ .Values.kuber.replicaCount }}
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      serviceAccountName: {{ include "kubectyl.serviceAccountName" . }}
      initContainers:
      - name: tmp
        image: busybox
        command: ["sh", "-c", "cp /tmp/kubectyl/config.yml /etc/kubectyl/config.yml"]
        volumeMounts:
          - name: config
            mountPath: "/tmp/kubectyl"
          - name: tmp
            mountPath: "/etc/kubectyl"
      containers:
      - name: kuber
        image: {{ .Values.kuber.image }}
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/kubectyl/certs
            readOnly: true
          - name: tmp
            mountPath: "/etc/kubectyl"
      volumes:
        - name: ssl-certs
          secret:
            secretName: {{ .Release.Name }}-tls
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: kuber-config
            defaultMode: 0755       
