apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "panel.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: panel
  serviceName: panel
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: panel
    spec:
      serviceAccountName: {{ include "kubectyl.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: panel
        image: {{ .Values.panel.image }}
        envFrom:
        - configMapRef:
            name: panel-config
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/nginx/certs
          readOnly: true
        - name: panel
          mountPath: /app/var/
          subPath: var
        - name: panel
          mountPath: /etc/nginx/http.d/
          subPath: nginx
        - name: panel
          mountPath: /app/storage/logs/
          subPath: logs
      volumes:
        - name: ssl-certs
          secret:
            secretName: {{ .Release.Name }}-tls
  volumeClaimTemplates:
  - metadata:
      name: panel
    spec:
      accessModes:
      - "ReadWriteOnce"
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: 1Gi
